### ISSUE TITLE
Add option to provide artefact basename 

### ISSUE THREAD

**Issue by dasheck0** [appcom-interactive/android-versioning#1]
Currently there is no way to provide the artefact basename. Therefore one has to override it by accessing the artefact, which is a hassle. As far as I see the artefact name is build by the following rule

`basename-versionname.versioncode-stage.apk`

It would be nice to set the basename and the stage (or the option of the stage should be used to begin with) by providing variables in the default config of the android block in the app/build.gradle file. Example:

```
android {
  defaultConfig {
    ...
    versioningBasename "myproject"
    versioningUseStage false
  }
}  
```

**Comment by G00fY2** [comment]
Added with 1.0.0.
